server:
  port: 8080
  servlet:
    context-path: /backend

spring:
  application:
    name: kockpit-audit-backoffice

kockpit:
  audit:
    azure:
      search:
        index_name: ${AZURESEARCH_INDEX}
        endpoint: ${AZURESEARCH_ENDPOINT}
        api_key: ${AZURESEARCH_APIKEY}

management:
  endpoint:
    health:
      probes:
        enabled: true
