openapi: 3.0.0
info:
  description: Kockpit Backend API
  title: Kockpit backend api
  version: "1.0"

paths:

  /backend/api/config:
    get:
      operationId: get config
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/config"

  /backend/api/{domain}/{env}/audits:
    get:
      operationId: listAuditsDomainEnv
      tags:
        - audits
      parameters:
        - name: domain
          in: path
          required: true
          schema:
            type: string
        - name: env
          in: path
          required: true
          schema:
            type: string
        - name: start
          description: number of elements to skip
          in: query
          schema:
            type: integer
            default: 0
        - name: size
          description: number of items to return
          in: query
          schema:
            type: integer
            default: 50

      description: list audits, for env and domain
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/page"

  /backend/api/audits/{id}:
    get:
      operationId: auditById
      tags:
        - audit
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object

  /backend/api/{domain}/{env}/audits/{id}:
    get:
      operationId: auditByIdForEnvAndDomain
      tags:
        - audit
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: domain
          in: path
          required: true
          schema:
            type: string
        - name: env
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object

  /backend/api/{domain}/{env}/audits/{id}/requests:
    get:
      operationId: auditReportRequestsById
      tags:
        - audit reports requests
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: domain
          in: path
          required: true
          schema:
            type: string
        - name: env
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object

  /backend/api/{domain}/{env}/audits/_search:
    get:
      operationId: searchAudits
      tags:
        - audits
      parameters:
        - name: query
          in: query
          required: true
          schema:
            type: string
        - name: domain
          in: path
          required: true
          schema:
            type: string
        - name: env
          in: path
          required: true
          schema:
            type: string
        - name: start
          description: number of elements to skip
          in: query
          schema:
            type: integer
            default: 0
        - name: size
          description: number of items to return
          in: query
          schema:
            type: integer
            default: 50

      description: search audits
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/page"

components:
  schemas:
    config:
      type: array
      items:
        $ref: "#/components/schemas/config_item"

    config_item:
      type: object
      properties:
        domain:
          type: string
        env:
          type: string
        services:
          type: array
          items:
            $ref: "#/components/schemas/service"

    service:
      type: object
      properties:
        name:
          type: string
        config:
          oneOf:
            - $ref: "#/components/schemas/config_audit"

    config_audit:
      type: object
      properties:
        columns:
          type: array
          items:
            type: string

    config_envs:
      type: array
      items:
        format: object
        properties:
          domain:
            type: string
          env:
            type: string

    page:
      type: object
      properties:
        total_count:
          type: integer
          format: int64
        size:
          type: integer
          format: int64
        items:
          type: array
          items:
            format: object
