openapi: 3.0.0
info:
  description: Kockpit Backend API
  title: Kockpit backend api
  version: "1.0"
paths:
  /backend/api/configs/envs:
    get:
      operationId: list environments
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/config_envs"

  /backend/api/audits:
    get:
      operationId: listAudits
      tags:
        - audits
      description: list audits
      parameters:
        - name: start
          description: number of elements to skip
          in: query
          schema:
            type: integer
            default: 0
        - name: size
          description: number of items to return
          in: query
          schema:
            type: integer
            default: 50

      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/page"

  /backend/api/audits/_search:
    get:
      operationId: searchAudits
      tags:
        - audits
      parameters:
        - name: query
          in: query
          required: true
          schema:
            type: string
      description: list audits
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/page"

  /backend/api/{domain}/{env}/audits:
    get:
      operationId: listAuditsDomainEnv
      tags:
        - audits
      parameters:
        - name: domain
          in: path
          required: true
          schema:
            type: string
        - name: env
          in: path
          required: true
          schema:
            type: string
        - name: start
          description: number of elements to skip
          in: query
          schema:
            type: integer
            default: 0
        - name: size
          description: number of items to return
          in: query
          schema:
            type: integer
            default: 50

      description: list audits, for env and domain
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/page"

  /backend/api/audit-reports:
    get:
      operationId: listAuditReports
      tags:
        - auditReports
      description: list all audit reports
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  format: object

  /backend/api/audit-reports/{id}/requests:
    get:
      operationId: auditReportRequestsById
      tags:
        - audit reports requests
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object

  /backend/api/audit-reports/{id}/requests/{traceId}:
    get:
      operationId: auditReportRequestsByIdAndTraceId
      tags:
        - audit reports requests
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: traceId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object

  /backend/api/audit-reports/{id}:
    get:
      operationId: auditReportById
      tags:
        - audit reports
      description: details of an audit report
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object

components:
  schemas:
    config_envs:
      type: array
      items:
        format: object
        properties:
          domain:
            type: string
          env:
            type: string

    page:
      type: object
      properties:
        total_count:
          type: integer
          format: int64
        size:
          type: integer
          format: int64
        items:
          type: array
          items:
            format: object
