server:
  port: 8080
  servlet:
    context-path: /sample-basic

spring:
  cloud:
    azure:
      eventhubs:
        namespace: eh-ns
        event-hub-name: eh1
        consumer:
          consumer-group: $default
        connection-string: Endpoint=sb://localhost;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;

