AZURESEARCH_INDEX: audit-v2
AZURESEARCH_ENDPOINT: https://rcu-dev.search.windows.net
AZURESEARCH_APIKEY: JAlCjsGXNDCnncUtpl1RzqiDO4DRisg8LURymqWX8KAzSeCr0p1w

STORAGE_ENDPOINT: https://kockpitreferential.blob.core.windows.net/
STORAGE_KEY: 91hs5gcFadHXXTYQDtMshqd9K3OJvehRjeL2tiiaAbnIUiLtG5Wd4MK77SZXVQyZvTP/i8ksjzb4+AStB8uwqg==
STORAGE_ACCOUNT: kockpitreferential
STORAGE_CONTAINER: referential
STORAGE_BLOB: manifests

