server:
  port: 8080
  servlet:
    context-path: /sample-basic

logging:
  level:
    org.kockpit: TRACE

kockpit:
  sdk:
    domain: kockpit-samples
    env: local
    appId: sample-basic
    service:
      audit:
        web:
          disabled: false
        ttl.default: 5
        notification:
          async: true