openapi: 3.0.0
info:
  description: Kockpit Backend API
  title: Kockpit backend api
  version: "1.0"

paths:

  /config:
    get:
      operationId: getConfig
      tags:
        - config
        - manifest
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/config"

  /{domain}/{env}/dyna-config:
    get:
      operationId: dynaConfig
      tags:
        - dynaConfig
      parameters:
        - name: domain
          in: path
          required: true
          schema:
            type: string
        - name: env
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object

  /{domain}/{env}/audits:
    get:
      operationId: listAudits
      tags:
        - audits
      parameters:
        - name: domain
          in: path
          required: true
          schema:
            type: string
        - name: env
          in: path
          required: true
          schema:
            type: string
        - name: start
          description: number of elements to skip
          in: query
          schema:
            type: integer
            default: 0
        - name: size
          description: number of items to return
          in: query
          schema:
            type: integer
            default: 50

      description: list audits, for env and domain
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/page"

  /audits/{id}:
    get:
      operationId: auditById
      tags:
        - audits
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object

  /{domain}/{env}/audits/{id}:
    get:
      operationId: auditsByIdForDomainAndEnv
      tags:
        - audits
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: domain
          in: path
          required: true
          schema:
            type: string
        - name: env
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object

  /{domain}/{env}/audits/_search:
    post:
      operationId: searchAuditsPost
      tags:
        - audits
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/searchTerms"
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/page"
      parameters:
        - name: domain
          in: path
          required: true
          schema:
            type: string
        - name: env
          in: path
          required: true
          schema:
            type: string
        - name: start
          description: number of elements to skip
          in: query
          schema:
            type: integer
            default: 0
        - name: size
          description: number of items to return
          in: query
          schema:
            type: integer
            default: 50

    get:
      operationId: searchAudits
      tags:
        - audits
      parameters:
        - name: query
          in: query
          required: true
          schema:
            type: string
        - name: domain
          in: path
          required: true
          schema:
            type: string
        - name: env
          in: path
          required: true
          schema:
            type: string
        - name: start
          description: number of elements to skip
          in: query
          schema:
            type: integer
            default: 0
        - name: size
          description: number of items to return
          in: query
          schema:
            type: integer
            default: 50

      description: search audits
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/page"

components:
  schemas:
    searchTerms:
      type: array
      items:
        $ref: "#/components/schemas/searchTerm"

    searchTerm:
      type: object
      properties:
        name:
          type: string
        path:
          type: string
        value:
          type: object

    config:
      type: array
      items:
        $ref: "#/components/schemas/config_item"

    config_item:
      type: object
      properties:
        domain:
          type: string
        env:
          type: string
        services:
          type: array
          items:
            $ref: "#/components/schemas/service"

    service:
      type: object
      properties:
        name:
          type: string
        config:
          type: object

    config_audit:
      type: object
      properties:
        columns:
          type: array
          items:
            type: string

    config_dynaconfig:
      type: object
      properties:
        keys:
          type: array
          items:
            $ref: "#/components/schemas/dynaconfig_key"

    dynaconfig_key:
      type: object
      properties:
        name:
          type: string
        value:
          type: string

    config_envs:
      type: array
      items:
        format: object
        properties:
          domain:
            type: string
          env:
            type: string

    page:
      type: object
      properties:
        total_count:
          type: integer
          format: int64
        size:
          type: integer
          format: int64
        items:
          type: array
          items:
            format: object
