include:
  - project: welcome-connect-platform/framework/templates/gitlabci
    ref: "java-21-kockpit"
    file: app-build-jib-ci.yml

variables:
  CI_JIB_PLATFORMS: "linux/arm64"

.runner-xxlarge:
  variables:
    KUBERNETES_SERVICE_CPU_REQUEST: "200m"
    KUBERNETES_SERVICE_CPU_LIMIT: "2"
    KUBERNETES_SERVICE_MEMORY_REQUEST: "2Gi"
    KUBERNETES_SERVICE_MEMORY_LIMIT: "4Gi"

.k8s-dind:
  variables:
    DOCKER_VERSION: 24.0.9
    # DOCKER_HOST: tcp://docker:2375
    # @k8s/gitlab-runner : hostAliases: are lost with variabilised DOCKER_VERSION..
    DOCKER_HOST: tcp://127.0.0.1:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:${DOCKER_VERSION}-dind

.mvn-test:
  extends:
    - .mvn-job
    - .k8s-dind
    - .runner-xxlarge

.mvn-release-prepare:
  extends:
    - .mvn-job
    - .k8s-dind
    - .runner-xxlarge
