include:
  - project: welcome-connect-platform/framework/templates/gitlabci
    ref: "java-17"
    file: lib-build-java-ci.yml

mvn-deploy-snapshot-feat:
  when: manual
  extends:
    - .mvn-deploy-snapshot
    - .mr
    - .runner-xlarge

mvn-build-mr:
  variables:
    CACHE_MODE: "true"
  cache:
    key: m2-cache
    policy: pull-push
    paths:
      - $CI_PROJECT_DIR/.m2/repository/

.mvn-job:
  extends:
    - .runner-xlarge

.mvn-build:
  extends:
    - .runner-xlarge
    - .mvn-job

.git-report-changes:
  extends: .runner-small

.mvn-sonar:
  extends:
    - .runner-xlarge
    - .mvn-job

.ms-team-notif:
  extends: .runner-micro

.mvn-cache:
  extends:
    - .mvn-sonar
    - .runner-xlarge
