<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.kockpit</groupId>
  <artifactId>kockpit</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>Kockpit</name>

  <organization>
    <name>Kockpit</name>
    <url>https://www.kockpit.org</url>
  </organization>

  <modules>
      <module>core</module>
      <module>config</module>
      <module>feature</module>
  </modules>

  <properties>
    <!-- Build properties -->
    <java.version>17</java.version>
    <maven.version>3.6.3</maven.version>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <maven.build.timestamp.format>yyyyMMddHHmmss</maven.build.timestamp.format>
    <maven.compiler.source>${java.version}</maven.compiler.source>
    <maven.compiler.target>${java.version}</maven.compiler.target>

      <mockserver-client-java.version>5.15.0</mockserver-client-java.version>
      <kafka-clients.version>3.8.1</kafka-clients.version>
      <mapstruct.version>1.6.3</mapstruct.version>
      <commons-text.version>1.13.0</commons-text.version>
      <commons-collections4.version>4.4</commons-collections4.version>
      <amazon-kinesis-client.version>3.0.1</amazon-kinesis-client.version>
      <lombok.version>1.18.38</lombok.version>
      <spring-boot-dependencies.version>3.5.4</spring-boot-dependencies.version>
      <awssdk.bom.version>2.32.14</awssdk.bom.version>
      <spring-framework-bom.version>6.2.9</spring-framework-bom.version>
      <commons-beanutils.version>1.9.4</commons-beanutils.version>
  </properties>

  <scm>
    <connection>
      scm:git:https://gitlab.softfactory-accor.net/welcome-connect-platform/kockpit-projects/kockpit.git
    </connection>
    <url>https://gitlab.softfactory-accor.net/welcome-connect-platform/kockpit-projects/kockpit
    </url>
    <developerConnection>scm:git:git@gitlab.softfactory-accor.net:welcome-connect-platform/kockpit-projects/kockpit.git</developerConnection>
    <tag>HEAD</tag>
  </scm>

  <distributionManagement>
    <snapshotRepository>
      <id>deployment_snapshot</id> <!-- Software Factory Sonatype Repository Manager-->
      <url>https://nexus.softfactory-accor.net/repository/maven-snapshots/</url>
    </snapshotRepository>
    <repository>
      <id>deployment_release</id> <!-- Software Factory Sonatype Repository Manager-->
      <url>https://nexus.softfactory-accor.net/repository/maven-releases/</url>
    </repository>
  </distributionManagement>

    <dependencies>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.skyscreamer</groupId>
            <artifactId>jsonassert</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-framework-bom</artifactId>
                <version>${spring-framework-bom.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>software.amazon.awssdk</groupId>
                <artifactId>bom</artifactId>
                <version>${awssdk.bom.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot-dependencies.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
            </dependency>
            <dependency>
                <groupId>software.amazon.kinesis</groupId>
                <artifactId>amazon-kinesis-client</artifactId>
                <version>${amazon-kinesis-client.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-collections4</artifactId>
                <version>${commons-collections4.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-text</artifactId>
                <version>${commons-text.version}</version>
            </dependency>
            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct</artifactId>
                <version>${mapstruct.version}</version>
            </dependency>
            <dependency>
                <groupId>commons-beanutils</groupId>
                <artifactId>commons-beanutils</artifactId>
                <version>${commons-beanutils.version}</version>
            </dependency>

            <dependency>
                <groupId>org.mock-server</groupId>
                <artifactId>mockserver-netty</artifactId>
                <version>${mockserver-client-java.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.mock-server</groupId>
                <artifactId>mockserver-client-java</artifactId>
                <version>${mockserver-client-java.version}</version>
                <scope>test</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
