<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.4.3</version>
	</parent>
	<groupId>org.kockpit</groupId>
	<artifactId>kockpit</artifactId>
	<version>1.0.0-SNAPSHOT</version>
	<packaging>pom</packaging>

	<scm>
		<connection>scm:git:https://github.com/mahieddine-ichir/kockpit.git</connection>
	</scm>

	<modules>
		<module>kockpit-audit</module>
		<module>kockpit-rules</module>
		<module>kockpit-backends</module>
        <module>kockpit-samples</module>
        <module>kockpit-samples/kockpit-sample-all</module>
    </modules>

	<profiles>
		<profile>
			<id>stime</id>
			<distributionManagement>
				<repository>
					<id>releases</id>
					<url>https://pkgs.dev.azure.com/mousquetaires-rcu/_packaging/releases/maven/v1</url>
				</repository>
				<snapshotRepository>
					<id>snapshots</id>
					<url>https://pkgs.dev.azure.com/mousquetaires-rcu/_packaging/snapshots/maven/v1</url>
				</snapshotRepository>
			</distributionManagement>
			<repositories>
				<repository>
					<id>snapshots</id>
					<url>https://pkgs.dev.azure.com/mousquetaires-rcu/_packaging/snapshots/maven/v1</url>
					<releases>
						<enabled>false</enabled>
					</releases>
					<snapshots>
						<enabled>true</enabled>
					</snapshots>
				</repository>
				<repository>
					<id>releases</id>
					<url>https://pkgs.dev.azure.com/mousquetaires-rcu/_packaging/releases/maven/v1</url>
					<releases>
						<enabled>true</enabled>
					</releases>
					<snapshots>
						<enabled>false</enabled>
					</snapshots>
				</repository>
			</repositories>
			<pluginRepositories>
				<pluginRepository>
					<name>snapshots</name>
					<id>snapshots</id>
					<url>https://pkgs.dev.azure.com/mousquetaires-rcu/_packaging/snapshots/maven/v1</url>
				</pluginRepository>
			</pluginRepositories>
		</profile>

		<profile>
			<id>central</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.sonatype.central</groupId>
						<artifactId>central-publishing-maven-plugin</artifactId>
						<version>0.7.0</version>
						<extensions>true</extensions>
						<configuration>
							<publishingServerId>central</publishingServerId>
						</configuration>
					</plugin>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-source-plugin</artifactId>
						<version>3.3.0</version>
						<executions>
							<execution>
								<id>attach-sources</id>
								<phase>verify</phase>
								<goals>
									<goal>jar-no-fork</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-javadoc-plugin</artifactId>
						<version>3.6.3</version>
						<executions>
							<execution>
								<id>attach-javadoc</id>
								<goals>
									<goal>jar</goal>
								</goals>
							</execution>
						</executions>
						<configuration>
							<stylesheet>java</stylesheet>
							<doclint>none</doclint>
							<additionalOptions>-package</additionalOptions>
						</configuration>
					</plugin>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-gpg-plugin</artifactId>
						<version>3.2.6</version>
						<executions>
							<execution>
								<id>sign-artifacts</id>
								<phase>verify</phase>
								<goals>
									<goal>sign</goal>
								</goals>
							</execution>
						</executions>
						<configuration>
							<gpgArguments>
								<arg>--pinentry-mode</arg>
								<arg>loopback</arg>
							</gpgArguments>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>
