version: '3.8'
services:
  opensearch:
    container_name: opensearch_2_0_0
    image: opensearchproject/opensearch:2.0.0
    environment:
      - cluster.name=audit-cluster
      - node.name=audit-node
      - discovery.type=single-node
      - plugins.security.disabled=true
      - network.host=0.0.0.0
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"