server.port=8080
server.servlet.context-path=/backend/api

spring.application.name=kockpit-audit
kockpit.audit.opensearch.host=localhost
kockpit.audit.opensearch.port=9200
kockpit.audit.opensearch.index=audit-index
kockpit.audit.opensearch.scheme=https
kockpit.audit.opensearch.username=admin
kockpit.audit.opensearch.password=StrongPass#2025

logging.level.org.springframework.security=warn
logging.level.org.kockpit=debug
