<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.kockpit</groupId>
        <artifactId>kockpit-samples</artifactId><version>1.0.2-beta</version>
    </parent>

    <artifactId>kockpit-sample-all</artifactId>
    <name>Kockpit Sample All</name>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.kockpit</groupId>
            <artifactId>kockpit-core-communication-polling</artifactId>
            <version>1.0.2-beta</version>
        </dependency>
        <dependency>
            <groupId>org.kockpit</groupId>
            <artifactId>kockpit-features-featureflipping-service</artifactId>
            <version>1.0.2-beta</version>
        </dependency>
        <dependency>
            <groupId>org.kockpit</groupId>
            <artifactId>kockpit-features-heartbeat-service-application</artifactId>
            <version>1.0.2-beta</version>
        </dependency>
    </dependencies>

    <profiles>
        <!-- storage-based features communication layer -->
        <profile>
            <id>azure</id>
            <dependencies>
                <dependency>
                    <groupId>org.kockpit</groupId>
                    <artifactId>kockpit-core-communication-storageaccount</artifactId>
                    <version>1.0.2-beta</version>
                </dependency>
                <dependency>
                    <groupId>org.kockpit</groupId>
                    <artifactId>kockpit-features-audit-starters-kafka</artifactId>
                    <version>1.0.2-beta</version>
                </dependency>
            </dependencies>
        </profile>
        <profile>
            <id>filesystem</id>
            <dependencies>
                <dependency>
                    <groupId>org.kockpit</groupId>
                    <artifactId>kockpit-core-communication-filesystem</artifactId>
                    <version>1.0.2-beta</version>
                </dependency>
                <dependency>
                    <groupId>org.kockpit</groupId>
                    <artifactId>kockpit-features-audit-starters-kafka</artifactId>
                    <version>1.0.2-beta</version>
                </dependency>
            </dependencies>
        </profile>
        <profile>
            <id>aws</id>
            <dependencies>
                <dependency>
                    <groupId>org.kockpit</groupId>
                    <artifactId>kockpit-core-communication-s3</artifactId>
                    <version>1.0.2-beta</version>
                </dependency>
                <dependency>
                    <groupId>org.kockpit</groupId>
                    <artifactId>kockpit-features-audit-starters-kinesis</artifactId>
                    <version>1.0.2-beta</version>
                </dependency>
            </dependencies>
        </profile>
    </profiles>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <mainClass>org.kockpit.sample.KockpitSampleApplication</mainClass>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>build-info</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
