spring:
  application:
    name: kockpit-kinesis-s3

aws:
  region: ${AWS_REGION:us-east-1}

kockpit:
  kinesis-to-s3:
    kinesis:
      stream-names: ${KINESIS_STREAM_NAMES}
      endpoint: ${KINESIS_ENDPOINT:}
      read-interval-ms: ${KINESIS_READ_INTERVAL_MS:5000}
      record-limit: ${KINESIS_RECORD_LIMIT:100}
    s3:
      bucket: ${S3_BUCKET}
      endpoint: ${S3_ENDPOINT:}

management:
  endpoints:
    web:
      exposure:
        include: health,info