<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.kockpit</groupId>
        <artifactId>kockpit-features-audit</artifactId>
        <version>1.0.2-beta</version>
    </parent>
    <artifactId>kockpit-features-audit-starters</artifactId>
    <name>Kockpit Audit Starter</name>
    <packaging>pom</packaging>
    <modules>
        <module>kockpit-features-audit-starters-kafka</module>
        <module>kockpit-features-audit-starters-kinesis</module>
    </modules>


</project>
