package com.accor.wcp.web.rest.config;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Data;

@Data
@AllArgsConstructor
public class FakeUser {

  private String name;

  private Integer age;

  private String email;

  private String message;

  private UserOrigin origin;

  @NotBlank
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  @Min(1)
  @Max(150)
  public Integer getAge() {
    return age;
  }

  public void setAge(Integer age) {
    this.age = age;
  }

  @Email
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  @Size(min = 10, max = 100)
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  @JsonIgnoreProperties(
      value =
          "type", // ignore manually set type, it will be automatically generated by Jackson during
      // serialization
      allowSetters = true // allows the type to be set during deserialization
      )
  @JsonTypeInfo(
      use = JsonTypeInfo.Id.NAME,
      include = JsonTypeInfo.As.PROPERTY,
      property = "type",
      visible = true)
  @JsonSubTypes({
    @JsonSubTypes.Type(value = NewOrigin.class, name = "NEW"),
    @JsonSubTypes.Type(value = OldOrigin.class, name = "OLD")
  })
  private class UserOrigin {
    private String id;
  }

  private class NewOrigin extends UserOrigin {}

  private class OldOrigin extends UserOrigin {}
}
