<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.kockpit</groupId>
        <artifactId>kockpit-rules-engine-parent</artifactId>
        <version>1.0.0-beta</version>
    </parent>
    <artifactId>kockpit-rules-starter</artifactId>

    <dependencies>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
            <version>6.2.5</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
            <version>3.4.4</version>
        </dependency>
        <dependency>
            <groupId>org.kockpit</groupId>
            <artifactId>kockpit-rules-executor</artifactId>
            <version>1.0.0-beta</version>
        </dependency>
        <dependency>
            <groupId>org.kockpit</groupId>
            <artifactId>kockpit-rules-definition</artifactId>
            <version>1.0.0-beta</version>
        </dependency>
        <dependency>
            <groupId>org.kockpit</groupId>
            <artifactId>kockpit-rules-registry</artifactId>
            <version>1.0.0-beta</version>
        </dependency>
    </dependencies>

</project>