<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.kockpit</groupId>
        <artifactId>kockpit-audit-stream</artifactId><version>1.0.2-beta</version>
    </parent>
    <artifactId>kockpit-audit-stream-application</artifactId>
    <name>Kockpit Audit Stream Application</name>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.kockpit</groupId>
            <artifactId>kockpit-audit-stream-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
            <version>1.6.3</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.opensearch.client</groupId>
            <artifactId>opensearch-rest-high-level-client</artifactId>
            <version>3.3.2</version>
        </dependency>
        <!-- features -->
        <dependency>
            <groupId>org.kockpit</groupId>
            <artifactId>kockpit-features-audit-module-web</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>1.6.3</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <mainClass>org.kockpit.audit.stream.KockpitStreamApplication</mainClass>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>build-info</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>kafka</id>
            <dependencies>
                <dependency>
                    <groupId>org.kockpit</groupId>
                    <artifactId>kockpit-audit-stream-starter-kafka</artifactId>
                    <version>1.0.2-beta</version>
                </dependency>
                <dependency>
                    <groupId>org.kockpit</groupId>
                    <artifactId>kockpit-audit-notification-kafka</artifactId>
                    <version>1.0.2-beta</version>
                </dependency>
            </dependencies>
            <build>
                <finalName>${project.artifactId}-kafka-${project.version}</finalName>
            </build>
        </profile>
        <profile>
            <id>aws</id>
            <dependencies>
                <dependency>
                    <groupId>org.kockpit</groupId>
                    <artifactId>kockpit-audit-stream-starter-kinesis</artifactId>
                    <version>1.0.2-beta</version>
                </dependency>
                <dependency>
                    <groupId>org.kockpit</groupId>
                    <artifactId>kockpit-audit-notification-kinesis</artifactId>
                    <version>1.0.2-beta</version>
                </dependency>
                <dependency>
                    <groupId>org.kockpit</groupId>
                    <artifactId>kockpit-aws-opensearch-request-signing</artifactId>
                    <version>1.0.2-beta</version>
                </dependency>
            </dependencies>
            <build>
                <finalName>${project.artifactId}-aws-${project.version}</finalName>
            </build>
        </profile>
    </profiles>
</project>
