<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>org.kockpit</groupId>
        <artifactId>kockpit-feature</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>kockpit-feature-dynacache</artifactId>
    <name>Welcome Connect Platform - Service - Dynacache</name>
    <packaging>pom</packaging>

    <modules>
        <module>dynacache-communication</module>
        <module>dynacache-console-backend</module>
        <module>dynacache-application</module>
    </modules>
</project>
