spring:
  kafka:
    bootstrap-servers:
      - ${BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${spring.application.name}
      max-poll-records: 50

kockpit:
  audit:
    stream:
      kafka:
        topics: audit
      opensearch:
        endpoints: ${OPENSEARCH_ENDPOINTS:http://localhost:9200}
        index_suffix: audit-data
