server:
  port: 8081

spring:
  application:
    name: kockpit-audit-stream
  kafka:
    bootstrap-servers:
      - ${BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${spring.application.name}
      max-poll-records: 50

management:
  server:
    port: 8091


kockpit:
  domain: kockpit
  env: local
  appId: ${spring.application.name}
  aws.region: eu-west-1

  audit:
    stream:
      s3:
        bucket_name: audits-${kockpit.env}
        allowed_ttl_days: 1,7,14,30,60,90,120
      consumer: opensearch-s3
      opensearch:
        endpoints: ${OPENSEARCH_ENDPOINTS:localhost:9200}
        index_suffix: ${INDEX_SUFFIX:audit-data}
        ttl_default_in_days: 5
      kafka:
        topics: audits
      kinesis:
        efo:
          consumer_name: ${spring.application.name}
        stream_name: ${KINESIS_STREAM_NAME}
        application_name: ${KINESIS_APP_NAME:${kockpit.appId}}
        timeout:
          connection: 5000
          socket: 30000

    # application services
    ttl_default_in_days: 1
    notification:
      kafka:
        topic: ${NOTIFICATION_TOPIC:audits}
      kinesis:
        stream_name: ${KINESIS_STREAM_NAME:auditstream}

aws.region: eu-west-1
