kockpit:
  audit:
    stream:
      kinesis:
        streamName: auditstream-local
        timeout:
          connection: 5000
          socket: 30000
      opensearch:
        endpoints: ${OPENSEARCH_ENDPOINTS:http://localhost:9200}
        index_suffix: audit-data
