server:
  port: 8080

spring:
  cloud:
    azure:
      eventhubs:
        namespace: kockpit-pro
        event-hub-name: kockpit
        consumer:
          consumer-group: audit-stream
        connection-string: Endpoint=sb://kockpit-pro.servicebus.windows.net/;SharedAccessKeyName=audit-sender;SharedAccessKey=IglvzyvO2jvAA2hNqyh2vI+s7ARL4xUQx+AEhBv/Q3k=;EntityPath=kockpit

management:
  endpoint:
    health:
      probes:
        enabled: true

kockpit:
  audit:
    stream:
      azure:
        search:
          index_name: audit-v2
          endpoint: https://kockpit-pro.search.windows.net
          api_key: 2dOlEcmQDsTkTG08Xq5evsB8jvSOtnWoRzADme8LOEAzSeCbat1m