services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_NUM_PARTITIONS=3

  opensearch:
    image: opensearchproject/opensearch:3.2.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - DISABLE_SECURITY_PLUGIN=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - opensearch-data:/usr/share/opensearch/data
      - ./opensearch/data:/init-data
      - ./opensearch/scripts:/docker-entrypoint-init.d
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 5

  dashboards:
    image: opensearchproject/opensearch-dashboards:3.2.0
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      - OPENSEARCH_HOSTS=["http://opensearch:9200"]
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true

  kockpit-backend-application:
    image: ghcr.io/mahieddine-ichir/kockpit/kockpit-backend-application-filesystem:latest
    container_name: kockpit-backend-application
    ports:
      - "8080:8080"
    environment:
      - OPENSEARCH_ENDPOINTS=http://opensearch:9200
      - kockpit.sdk.manifest.filesystem.path=/data/manifests
      - kockpit.sdk.filesystem.local_directory=/data
    volumes:
      - ~/IdeaProjects/kockpit/data:/data
    links:
      - opensearch:opensearch

  kockpit-console:
    image: ghcr.io/mahieddine-ichir/kockpit/kockpit-console:latest
    container_name: kockpit-console
    ports:
      - "3000:80"
    environment:
      - KOCKPIT_BACKEND=http://kockpit-backend-application:8080/backend
    links:
      - kockpit-backend-application:kockpit-backend-application
    depends_on:
      - kockpit-backend-application

volumes:
  opensearch-data:
