<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.kockpit</groupId>
    <artifactId>kockpit-audit-rules</artifactId><version>1.0.2-beta</version>
  </parent>
  <artifactId>kockpit-audit-rules-starter</artifactId>
    <name>Kockpit Audit Rules Starter</name>

  <dependencies>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.kockpit</groupId>
      <artifactId>kockpit-audit-api</artifactId>
      <version>1.0.2-beta</version>
    </dependency>
    <dependency>
      <groupId>org.kockpit</groupId>
      <artifactId>kockpit-audit-rules-impl</artifactId>
      <version>1.0.2-beta</version>
    </dependency>
    <dependency>
      <groupId>org.kockpit</groupId>
      <artifactId>kockpit-rules-registry-data</artifactId>
      <version>1.0.2-beta</version>
    </dependency>
    <dependency>
      <groupId>org.kockpit</groupId>
      <artifactId>kockpit-rules-registry</artifactId>
      <version>1.0.2-beta</version>
    </dependency>
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
    </dependency>
    <dependency>
      <groupId>org.kockpit</groupId>
      <artifactId>kockpit-rules-executor</artifactId>
      <version>1.0.2-beta</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.kockpit</groupId>
      <artifactId>kockpit-audit-annotation</artifactId>
      <version>1.0.2-beta</version>
    </dependency>
  </dependencies>
</project>
