/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.13.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.kockpit.backend.services.search;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping("/{domain}/{env}/audits")
@Tag(name = "audits", description = "the audits API")
@RequiredArgsConstructor
public class SearchApi {

    private final SearchService searchService;

    /**
     * GET /{domain}/{env}/audits/{id}
     *
     * @param id  (required)
     * @param domain  (required)
     * @param env  (required)
     * @return Successful operation (status code 200)
     */
    @Operation(
        operationId = "auditsByIdForDomainAndEnv",
        tags = { "audits" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful operation", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Object.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/{id}",
        produces = { "application/json" }
    )
    ResponseEntity<Object> auditsById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH)
            @PathVariable("id") String id,
        @Parameter(name = "domain", description = "", required = true, in = ParameterIn.PATH)
            @PathVariable("domain") String domain,
        @Parameter(name = "env", description = "", required = true, in = ParameterIn.PATH)
            @PathVariable("env") String env
    ) {
        Object audit = searchService.getAudit(domain, env, id);
        return ResponseEntity.ok(audit);
    }

    /**
     * GET /{domain}/{env}/audits
     * list audits, for env and domain
     *
     * @param domain  (required)
     * @param env  (required)
     * @param start number of elements to skip (optional, default to 0)
     * @param size number of items to return (optional, default to 50)
     * @return Successful operation (status code 200)
     */
    @Operation(
        operationId = "listAudits",
        description = "list audits, for env and domain",
        tags = { "audits" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful operation", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Page.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        produces = { "application/json" }
    )
    ResponseEntity<Page> listAudits(
        @Parameter(name = "domain", description = "", required = true, in = ParameterIn.PATH)
            @PathVariable("domain") String domain,
        @Parameter(name = "env", description = "", required = true, in = ParameterIn.PATH)
            @PathVariable("env") String env,
        @Parameter(name = "start", description = "number of elements to skip", in = ParameterIn.QUERY)
            @RequestParam(value = "start", required = false, defaultValue = "0") Integer start,
        @Parameter(name = "size", description = "number of items to return", in = ParameterIn.QUERY)
            @RequestParam(value = "size", required = false, defaultValue = "50") Integer size
    ) {
        Page page = searchService.listAudits(domain, env, start, size);
        return ResponseEntity.ok(page);
    }


    /**
     * GET /{domain}/{env}/audits/_search
     * search audits
     *
     * @param domain  (required)
     * @param env  (required)
     * @param query  (optional)
     * @param status  (optional)
     * @param start number of elements to skip (optional, default to 0)
     * @param size number of items to return (optional, default to 50)
     * @return Successful operation (status code 200)
     */
    @Operation(
        operationId = "searchAudits",
        description = "search audits",
        tags = { "audits" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful operation", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Page.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/_search",
        produces = { "application/json" }
    )
    ResponseEntity<Page> searchAudits(
            @Parameter(name = "domain", description = "", required = true, in = ParameterIn.PATH)
            @PathVariable("domain") String domain,
            @Parameter(name = "env", description = "", required = true, in = ParameterIn.PATH)
            @PathVariable("env") String env,
            @Parameter(name = "query", description = "", in = ParameterIn.QUERY)
            @RequestParam(value = "query", required = false) String query,
            @Parameter(name = "status", description = "", in = ParameterIn.QUERY)
            @RequestParam(value = "status", required = false) String status,
            @Parameter(name = "start", description = "number of elements to skip", in = ParameterIn.QUERY)
            @RequestParam(value = "start", required = false, defaultValue = "0") Integer start,
            @Parameter(name = "size", description = "number of items to return", in = ParameterIn.QUERY)
            @RequestParam(value = "size", required = false, defaultValue = "50") Integer size,
            @RequestBody List<SearchTerm> searchTerms
            ) {
        Page page = searchService.searchAudits(domain, env, query, searchTerms, start, size);
        return ResponseEntity.ok(page);
    }

    @GetMapping("/_search")
    ResponseEntity<Page> searchAuditsGet(
            @Parameter(name = "domain", description = "", required = true, in = ParameterIn.PATH)
            @PathVariable("domain") String domain,
            @Parameter(name = "env", description = "", required = true, in = ParameterIn.PATH)
            @PathVariable("env") String env,
            @Parameter(name = "query", description = "", in = ParameterIn.QUERY)
            @RequestParam(value = "query", required = false) String query,
            @Parameter(name = "status", description = "", in = ParameterIn.QUERY)
            @RequestParam(value = "status", required = false) String status,
            @Parameter(name = "start", description = "number of elements to skip", in = ParameterIn.QUERY)
            @RequestParam(value = "start", required = false, defaultValue = "0") Integer start,
            @Parameter(name = "size", description = "number of items to return", in = ParameterIn.QUERY)
            @RequestParam(value = "size", required = false, defaultValue = "50") Integer size
            ) {
        Page page = searchService.searchByQuery(domain, env, query, start, size);
        return ResponseEntity.ok(page);
    }

}
