<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.kockpit</groupId>
        <artifactId>kockpit-features</artifactId>
        <version>1.1.1-SNAPSHOT</version>
    </parent>

    <artifactId>kockpit-features-audit</artifactId>
    <packaging>pom</packaging>
    <name>Kockpit Features Audit</name>
    <modules>
        <module>kockpit-features-audit-module-web</module>
        <module>kockpit-features-audit-module-httpexchange</module>

        <module>kockpit-features-audit-notification</module>
        <module>kockpit-features-audit-starters</module>
    </modules>

</project>
