server.port: 8080
spring:
  application.name: mcp-server
  main.web-application-type: servlet
  main.banner-mode: off
  ai:
    mcp:
      server:
        name: mcp-server
        version: 2.0.0
        type: sync
        stdio: false
        protocol: stateless
        streamable-http:
          keep-alive-interval: 30s
          mcp-endpoint: /mcp

logging.pattern.console:

opensearch:
    endpoints: localhost:9200
