
kockpit:
  sdk:
    domain: rcu
    env: local
    appId: sample-app
    filesystem:
      local_directory: ${user.home}/IdeaProjects/kockpit/data/feature-flipping

logging:
  level:
    org.kockpit: trace
