server:
  servlet:
    context-path: /sample-app
  port: 8082

spring:
  application:
    name: kockpit-samples-all
  kafka:
    producer:
      bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:9092}

kockpit:
  domain: kockpit
  env: local
  app-id: ${spring.application.name}

  communication:
    enabled: false
    polling:
      enabled: false

    azure:
      storage:
        account: ${STORAGE_ACCOUNT}
        endpoint: https://${kockpit.communication.azure.storage.account}.blob.core.windows.net
        key: ${STORAGE_KEY}
        container: ${STORAGE_CONTAINER:data}
    filesystem:
      enabled: false
      path: ${FS_STORAGE_PATH}

    poller:
      scheduling: PT30S

  audit:
    trace:
      enabled: false
    notification:
      async-delay-ms: 60000
      kafka:
        topic: audits
      kinesis:
        stream_name: auditstream

  feature-flipping:
    client:
      scheduling: PT10S
    polling:
      enabled: true
  dyna-config:
    enabled: false
  heartbeat:
    enabled: false
    polling:
      enabled: false



logging:
  level:
    org.kockpit: TRACE
