
kockpit:
  sdk:
    domain: rcu
    env: local
    appId: sample-app

    feature-flipping:
      polling:
        enabled: true
    heartbeat:
      enabled: true
      polling:
        enabled: false

    filesystem:
      local_directory: ${user.home}/IdeaProjects/kockpit/data/

logging:
  level:
    org.kockpit: trace
