server:
  port: 9080

spring:
  application:
    name: kockpit-audit-stream
  kafka:
    bootstrap-servers:
      - ${BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${spring.application.name}
      max-poll-records: 50

management:
  endpoint:
    health:
      probes:
        enabled: true

kockpit:
  audit:
    stream:
      kafka:
        topics: audit
      opensearch:
        endpoints: ${OPENSEARCH_ENDPOINTS:http://localhost:9200}
        index_suffix: audit-data
