/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.13.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.kockpit.backend.services.storage;

import lombok.RequiredArgsConstructor;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequiredArgsConstructor
@RequestMapping("/config")
public class ConfigApi {

    private final ConfigApiService configApiService;

    @GetMapping(produces = MediaType.APPLICATION_JSON_VALUE)
    ResponseEntity<List<Manifest>> list() {
        return ResponseEntity.ok(configApiService.list());
    }

    @PostMapping
    ResponseEntity<ConfigItem> create(@RequestBody ConfigItem configItem) {
        ConfigItem created = configApiService.save(configItem);
        return ResponseEntity.ok(created);
    }
}
