<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.kockpit</groupId>
      <artifactId>kockpit-sample</artifactId>
    <version>1.0.0-SNAPSHOT</version>
  </parent>

  <artifactId>sample-app</artifactId>
    <version>1.0.0-SNAPSHOT</version>
  <name>Kockpit Platform Engineering - Sample - Rest App with KEngine and Audit</name>

  <properties>
      <start-class>com.accor.wcp.sample.WcpSampleApplicationApp</start-class>
      <openapi-generator-maven-plugin.version>7.10.0</openapi-generator-maven-plugin.version>
      <swagger-annotations-v3.version>2.2.27</swagger-annotations-v3.version>
  </properties>

  <dependencies>
      <dependency>
          <groupId>org.kockpit</groupId>
          <artifactId>starter-full-web</artifactId>
          <version>${project.version}</version>
      </dependency>
      <dependency>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-cache</artifactId>
      </dependency>
      <dependency>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-actuator</artifactId>
      </dependency>
      <dependency>
          <groupId>org.springframework</groupId>
          <artifactId>spring-webflux</artifactId>
      </dependency>
      <dependency>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-security</artifactId>
      </dependency>
      <dependency>
          <groupId>io.opentelemetry</groupId>
          <artifactId>opentelemetry-api</artifactId>
      </dependency>
      <dependency>
          <groupId>io.swagger.core.v3</groupId>
          <artifactId>swagger-annotations</artifactId>
          <version>${swagger-annotations-v3.version}</version>
      </dependency>
      <dependency>
          <groupId>io.swagger.core.v3</groupId>
          <artifactId>swagger-models</artifactId>
          <version>${swagger-annotations-v3.version}</version>
      </dependency>

    <dependency>
      <groupId>org.hibernate.validator</groupId>
      <artifactId>hibernate-validator</artifactId>
    </dependency>

    <dependency>
      <groupId>org.kockpit</groupId>
      <artifactId>dynacache-application</artifactId>
        <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.ehcache</groupId>
      <artifactId>ehcache</artifactId>
    </dependency>

<!--    <dependency>-->
<!--        <groupId>org.kockpit</groupId>-->
<!--      <artifactId>wcp-rest-api-config-squiggly</artifactId>-->
<!--      <version>${project.version}</version>-->
<!--    </dependency>-->
    <dependency>
        <groupId>org.kockpit</groupId>
      <artifactId>rest-api-handler-problem</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
        <groupId>org.kockpit</groupId>
      <artifactId>rest-api-validation-acceptversion</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
        <groupId>org.kockpit</groupId>
      <artifactId>rest-api-filter-traceid</artifactId>
      <version>${project.version}</version>
    </dependency>

    <dependency>
        <groupId>org.kockpit</groupId>
      <artifactId>rest-api-filter-contentlanguage</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
        <groupId>org.kockpit</groupId>
      <artifactId>rest-api-config-localeresolver</artifactId>
      <version>${project.version}</version>
    </dependency>

    <dependency>
        <groupId>org.kockpit</groupId>
      <artifactId>audit-module-autoconfigure-kafka</artifactId>
      <version>${project.version}</version>
    </dependency>

    <dependency>
      <groupId>org.springframework.kafka</groupId>
      <artifactId>spring-kafka</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.kafka</groupId>
      <artifactId>spring-kafka-test</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.avro</groupId>
      <artifactId>avro</artifactId>
    </dependency>
    <dependency>
      <groupId>io.confluent</groupId>
      <artifactId>kafka-avro-serializer</artifactId>
      <exclusions>
        <exclusion>
          <groupId>org.apache.zookeeper</groupId>
          <artifactId>zookeeper</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-contract-wiremock</artifactId>
      <scope>compile</scope>
    </dependency>
    <dependency>
        <groupId>org.kockpit</groupId>
      <artifactId>featureflipping-application-openfeature</artifactId>
      <version>${project.version}</version>
    </dependency>

    <dependency>
        <groupId>org.kockpit</groupId>
      <artifactId>featureflipping-application-openfeature</artifactId>
      <version>${project.version}</version>
    </dependency>

      <dependency>
          <groupId>org.hamcrest</groupId>
          <artifactId>hamcrest-core</artifactId>
          <scope>test</scope>
      </dependency>
      <dependency>
          <groupId>org.mockito</groupId>
          <artifactId>mockito-junit-jupiter</artifactId>
          <scope>test</scope>
      </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.openapitools</groupId>
        <artifactId>openapi-generator-maven-plugin</artifactId>
        <version>${openapi-generator-maven-plugin.version}</version>
        <configuration>
          <generateModelTests>false</generateModelTests>
          <generateApiTests>false</generateApiTests>
          <configOptions>
            <dateLibrary>java8</dateLibrary>
            <serializableModel>true</serializableModel>
            <openApiNullable>false</openApiNullable>
          </configOptions>
        </configuration>
        <executions>
          <execution>
            <id>server</id>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <inputSpec>${project.basedir}/src/main/resources/specs/api_1_0_0.yml</inputSpec>
              <generatorName>spring</generatorName>
<!--              <library>spring-http-interface</library>-->
              <library>spring-boot</library>
              <apiPackage>com.accor.wcp.sample.basket.api</apiPackage>
              <modelPackage>com.accor.wcp.sample.basket.api.model</modelPackage>
              <generateSupportingFiles>true</generateSupportingFiles>
              <supportingFilesToGenerate>
                ApiUtil.java
              </supportingFilesToGenerate>
              <generateApiTests>false</generateApiTests>
              <generateModelTests>false</generateModelTests>
              <inlineSchemaNameMappings>
<!--                <inlineSchemaNameMapping>Basket_allOf=Basket</inlineSchemaNameMapping>-->
<!--                <inlineSchemaNameMapping>HotelStayBasketItem_allOf=HotelStayBasketItem</inlineSchemaNameMapping>-->
<!--                <inlineSchemaNameMapping>StandaloneTreatmentBasketItem_allOf=StandaloneTreatmentBasketItem</inlineSchemaNameMapping>-->
              </inlineSchemaNameMappings>
              <configOptions>
                <useSpringBoot3>true</useSpringBoot3>
<!--                <skipDefaultInterface>true</skipDefaultInterface>-->
                <useBeanValidation>true</useBeanValidation>
                <returnSuccessCode>true</returnSuccessCode>
                <delegatePattern>true</delegatePattern>
<!--                <implicitHeaders>true</implicitHeaders>-->
<!--                <inlineSchemaNameMapping>false</inlineSchemaNameMapping>-->
<!--                <allow-inline-schemas>true</allow-inline-schemas>-->
<!--                <openapi-normalizer>REF_AS_PARENT_IN_ALLOF=true</openapi-normalizer>-->
              </configOptions>
            </configuration>
          </execution>
          <execution>
            <id>basket-inheritance</id>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <inputSpec>${project.basedir}/src/main/resources/specs/ci_normalInheritance.yml</inputSpec>
              <generatorName>spring</generatorName>
              <library>spring-boot</library>
              <apiPackage>com.accor.wcp.sample.basket.inheritance.api</apiPackage>
              <modelPackage>com.accor.wcp.sample.basket.inheritance.api.model</modelPackage>
              <generateSupportingFiles>true</generateSupportingFiles>
              <supportingFilesToGenerate>
                ApiUtil.java
              </supportingFilesToGenerate>
              <generateApiTests>false</generateApiTests>
              <generateModelTests>false</generateModelTests>
              <configOptions>
                <useSpringBoot3>true</useSpringBoot3>
                <!--                <skipDefaultInterface>true</skipDefaultInterface>-->
                <useBeanValidation>true</useBeanValidation>
                <returnSuccessCode>true</returnSuccessCode>
                <delegatePattern>true</delegatePattern>
                <!--                <implicitHeaders>true</implicitHeaders>-->
                <!--                <inlineSchemaNameMapping>false</inlineSchemaNameMapping>-->
                <!--                <allow-inline-schemas>true</allow-inline-schemas>-->
                <!--                <openapi-normalizer>REF_AS_PARENT_IN_ALLOF=true</openapi-normalizer>-->
              </configOptions>
            </configuration>
          </execution>
          <execution>
            <id>basket-polymorphism</id>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <inputSpec>${project.basedir}/src/main/resources/specs/ci_polymorphism.yml</inputSpec>
              <generatorName>spring</generatorName>
              <library>spring-boot</library>
              <apiPackage>com.accor.wcp.sample.basket.polymorphism.api</apiPackage>
              <modelPackage>com.accor.wcp.sample.basket.polymorphism.api.model</modelPackage>
              <generateSupportingFiles>true</generateSupportingFiles>
              <supportingFilesToGenerate>
                ApiUtil.java
              </supportingFilesToGenerate>
              <generateApiTests>false</generateApiTests>
              <generateModelTests>false</generateModelTests>
              <configOptions>
                <useSpringBoot3>true</useSpringBoot3>
                <useBeanValidation>true</useBeanValidation>
                <returnSuccessCode>true</returnSuccessCode>
                <delegatePattern>true</delegatePattern>
              </configOptions>
            </configuration>
          </execution>
          <!-- Client example
          <execution>
              <id>availability-client</id>
              <goals>
                  <goal>generate</goal>
              </goals>
              <configuration>
                  <inputSpec>${project.basedir}/src/main/resources/specs/availability_1_0_0.yml
                  </inputSpec>
                  <generatorName>java</generatorName>
                  <library>resttemplate</library>
                  <modelPackage>com.accor.wcbno.basket.client.availability.model</modelPackage>
                  <apiPackage>com.accor.wcbno.basket.client.availability.api</apiPackage>
              </configuration>
          </execution>
          -->
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.avro</groupId>
        <artifactId>avro-maven-plugin</artifactId>
        <version>${avro.version}</version>
        <executions>
          <execution>
            <phase>generate-sources</phase>
            <goals>
              <goal>schema</goal>
            </goals>
            <configuration>
              <sourceDirectory>${project.basedir}/src/main/java/com/accor/wcp/sample/kafka/avro</sourceDirectory>
              <fieldVisibility>PRIVATE</fieldVisibility>
              <stringType>String</stringType>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

  <profiles>
    <profile>
      <id>feature-flipping-validate</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.kockpit</groupId>
            <artifactId>featureflipping-maven-plugin</artifactId>
            <version>1.0.0-SNAPSHOT</version>
            <executions>
              <execution>
                <id>verify</id>
                <goals>
                  <goal>verify</goal>
                </goals>
                <configuration>
<!--                  <api-url>http://localhost:8082/ihm_api/public/api/services/wcp/local/featureflipping/wcpsamples</api-url>-->
                  <api-url>https://console.wcplatform-dev.aws.accor.com/ihm_api/public/api/services/wcplatform/dev/featureflipping/wcpsamples</api-url>
                  <fail-on-expired>false</fail-on-expired>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>
