<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>org.kockpit</groupId>
        <artifactId>kockpit-core</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>lib</artifactId>
    <packaging>pom</packaging>
    <name>Kockpit Platform Engineering - Core - Lib</name>

    <modules>
        <module>aws</module>
        <module>rest-api-handler-problem</module>
        <module>rest-api-filter-contentlanguage</module>
        <module>rest-api-filter-traceid</module>
        <module>rest-api-validation-acceptversion</module>
        <module>rest-api-config-localeresolver</module>
        <module>rest-api-config-accesslog</module>
        <module>rest-api-config-datetimeformat</module>
        <module>rest-api-config-locale</module>
        <module>rest-api-config-jackson</module>
        <module>rest-api-config-security</module>
        <module>rest-api-config-tomcat</module>
        <module>rest-api-handler-jsonparseur</module>
        <module>rest-api</module>
    </modules>

    <dependencies>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-core</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
