package com.accor.kengine.yaml;

import com.accor.kengine.Action;
import com.accor.kengine.DefaultDocumentationDetails;
import com.accor.kengine.DocumentationDetails;
import com.accor.kengine.RulePredicate;
import java.io.IOException;
import java.util.Collections;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import org.junit.Test;
import org.springframework.beans.factory.BeanFactory;
import org.springframework.beans.factory.support.DefaultListableBeanFactory;
import org.springframework.test.util.ReflectionTestUtils;

public class TestGenerateYamlFlow {

  @Test
  public void should_generate_and_register_flows_and_rules() throws IOException {
    List<Action> actions = generateActions();
    List<RulePredicate> rulePredicates = generateRulePredicates();
    YamlFlowAutoConfiguration yamlFlowAutoConfiguration =
        new YamlFlowAutoConfiguration(actions, rulePredicates, Optional.empty());
    BeanFactory beanFactory = new DefaultListableBeanFactory();
    yamlFlowAutoConfiguration.setBeanFactory(beanFactory);
    ReflectionTestUtils.setField(yamlFlowAutoConfiguration, "location", "/flows/");
    yamlFlowAutoConfiguration.generateFlows();

    assert beanFactory.containsBean("FLOW_EXAMPLE");
    assert beanFactory.containsBean("BR_DO_STUFF");
  }

  private List<RulePredicate> generateRulePredicates() {
    return Stream.of("PRE_IS_OK")
        .map(name -> new RulePredicate(x -> true, new DefaultDocumentationDetails(name, name)))
        .collect(Collectors.toList());
  }

  private List<Action> generateActions() {
    return Stream.of(
            "ACT_DO_SOMETHING",
            "ACT_DO_SOMETHING2",
            "ACT_DO_IF_OK",
            "ACT_DO_IF_NOK",
            "ACT_DO_ANYWAYS")
        .map(
            name ->
                new Action() {
                  @Override
                  public void execute(Object context) {}

                  @Override
                  public DocumentationDetails getDetails() {
                    return new DefaultDocumentationDetails(name, name);
                  }
                })
        .collect(Collectors.toList());
  }

  @Test
  public void should_generate_yaml_flow_with_customizer() throws IOException {
    List<Action> actions = generateActions();
    List<RulePredicate> rulePredicates = generateRulePredicates();
    YamlFlowAutoConfiguration yamlFlowAutoConfiguration =
        new YamlFlowAutoConfiguration(
            actions, rulePredicates, Optional.of(new TestYamlFlowCustomizer()));
    BeanFactory beanFactory = new DefaultListableBeanFactory();
    yamlFlowAutoConfiguration.setBeanFactory(beanFactory);
    ReflectionTestUtils.setField(yamlFlowAutoConfiguration, "location", "/alternative-flows/");
    yamlFlowAutoConfiguration.generateFlows();

    assert beanFactory.containsBean("FLOW_ALTERNATIVE_YAML");
    assert beanFactory.containsBean("BR_ALTERNATIVE_YAML");
  }

  private class TestYamlFlowCustomizer extends YamlFlowMapperCustomizer<AlternativeYamlFormat> {
    public TestYamlFlowCustomizer() {
      super(AlternativeYamlFormat.class);
    }

    @Override
    public YamlFlow generateFlow(AlternativeYamlFormat input) {
      return YamlFlow.builder()
          .name(input.getFlow())
          .details(input.getDescription())
          .rules(
              Collections.singletonList(
                  YamlRule.builder()
                      .name(input.getRule())
                      .details("This rule node is autogenerated")
                      .predicate(
                          YamlPredicate.builder()
                              .names(input.getPredicates())
                              .ok(YamlRule.builder().actions(input.getActions()).build())
                              .ko(YamlRule.builder().actions(input.getCallbacks()).build())
                              .build())
                      .build()))
          .build();
    }
  }
}
