name: Build UI
on:
  push:
    branches: ["accor"]

env:
  working_dir: ./core-application/console-ui

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./core-application/console-ui

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: ./core-application/console-ui/package-lock.json
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci
      - run: npm run build
        env:
          CI: false

      - name: Zip artifact
        run: |
          zip -r build_${date +%s}.zip dist/ && cp build_*.zip build_latest.zip

      - name: Deploy to s3
        uses: reggionick/s3-deploy@v4
        with:
          folder: .
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          #dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: /
          delete-removed: true
          no-cache: true
          private: true
          files-to-include: '{./*.zip}'
