server:
  port: 8080
  servlet:
    context-path: /backend/api

springdoc:
  api-docs:
    path: /api-docs

spring:
  application:
    name: kockpit-backend-application
  main:
    allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers:
      - ${BOOTSTRAP_SERVERS:localhost:9092}

management:
  endpoint:
    health:
      probes:
        enabled: true
  server:
    port: 8090

logging:
  level:
    org.kockpit.communication: error

kockpit:
  domain: kockpit
  env: local
  appId: ${spring.application.name}

  # backend services
  backend:
    opensearch:
      endpoints: ${OPENSEARCH_ENDPOINTS:http://localhost:9200}
      index: ${INDEX_NAME:audit-data}
    manifests:
      azure:
        storage:
          account: ${MANIFESTS_STORAGE_ACCOUNT}
          endpoint: https://${kockpit.backend.manifests.azure.storage.account}.blob.core.windows.net
          key: ${MANIFESTS_STORAGE_KEY}
          container: ${MANIFESTS_STORAGE_CONTAINER:manifests}
      filesystem:
        path: ${FS_MANIFESTS_PATH}

  # comm layer
  communication:
    azure:
      storage:
        account: ${STORAGE_ACCOUNT}
        endpoint: https://${kockpit.communication.azure.storage.account}.blob.core.windows.net
        key: ${STORAGE_KEY}
        container: ${STORAGE_CONTAINER:data}
    aws:
    filesystem:
      path: ${FS_STORAGE_PATH}

  # application services
  audit:
    ttl_default_in_days: 1
    notification:
      kafka:
        topic: ${NOTIFICATION_TOPIC:audits}


